// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6GA7U1N71V-2IM7hOogESxoCoDSUjm1U',
    appId: '1:1090821655655:web:86c52304e5f68b784058c2',
    messagingSenderId: '1090821655655',
    projectId: 'task-4f5f9',
    authDomain: 'task-4f5f9.firebaseapp.com',
    storageBucket: 'task-4f5f9.firebasestorage.app',
    measurementId: 'G-KJHF9CBWTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwtrtEc4-UrHcid3Q4htN0Svn4pOGBytM',
    appId: '1:1090821655655:android:7b8f3d2d55f157a64058c2',
    messagingSenderId: '1090821655655',
    projectId: 'task-4f5f9',
    storageBucket: 'task-4f5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5doqB5mxTOM0zbA0VZso5gwEeZu_e-Ik',
    appId: '1:1090821655655:ios:2b5486987cd8903b4058c2',
    messagingSenderId: '1090821655655',
    projectId: 'task-4f5f9',
    storageBucket: 'task-4f5f9.firebasestorage.app',
    iosClientId: '1090821655655-m3fvn1k4b6jfj0r9r56jatsiqml62ic5.apps.googleusercontent.com',
    iosBundleId: 'com.taskup.taskupFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5doqB5mxTOM0zbA0VZso5gwEeZu_e-Ik',
    appId: '1:1090821655655:ios:2b5486987cd8903b4058c2',
    messagingSenderId: '1090821655655',
    projectId: 'task-4f5f9',
    storageBucket: 'task-4f5f9.firebasestorage.app',
    iosClientId: '1090821655655-m3fvn1k4b6jfj0r9r56jatsiqml62ic5.apps.googleusercontent.com',
    iosBundleId: 'com.taskup.taskupFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6GA7U1N71V-2IM7hOogESxoCoDSUjm1U',
    appId: '1:1090821655655:web:8ee307a49993d6064058c2',
    messagingSenderId: '1090821655655',
    projectId: 'task-4f5f9',
    authDomain: 'task-4f5f9.firebaseapp.com',
    storageBucket: 'task-4f5f9.firebasestorage.app',
    measurementId: 'G-4Y9NNLG2PG',
  );
}
